-- Premium: tek abonelik (haftalık 99 TL). Nasıl Başvururum ve İş Başvuru Mektubu dahil.
-- Tier (standard/plus) ayrımı yok; iki hizmet de aynı premium abonelikle açılır.
-- premium_subscriptions tablosunda tier kolonu eklenmez.
